#!/usr/bin/env python

import argparse
import sys

import rospy
from hmi import Client, TimeoutException

# start the node
rospy.init_node('test_query', anonymous=True)
args = rospy.myargv(argv=sys.argv)

# parse the args
parser = argparse.ArgumentParser()
parser.add_argument('-s', '--server', nargs='?', default='hmi', help='Actionlib server')
parser.add_argument('query', nargs='?', default='apple|banana', help='Actionlib server')

args = parser.parse_args(args[1:])
server = args.server
query = args.query

# do the query
hmi = Client(server)
try:
    hmi.query(description='', grammar='T -> %s' % query, target="T")
except TimeoutException:
    pass
