#!/usr/bin/env python

"""
A HMI server that always responds with an empty result
"""

import rospy
from hmi import AbstractHMIServer, HMIResult


class HMIServer(AbstractHMIServer):
    def _determine_answer(self, description, grammar, target, is_preempt_requested):
        return HMIResult("sentence", {})


if __name__ == "__main__":
    rospy.init_node("noop_server")
    HMIServer(rospy.get_name())
    rospy.spin()
