#!/usr/bin/env python

import rospy
from hmi_msgs.msg import QueryAction, QueryResult, Result
from actionlib import SimpleActionServer
from random import choice as choose
from hmi_server.abstract_server import AbstractHMIServer


class HMIServer(AbstractHMIServer):

    def _determine_answer(self, description, spec, choices):
        results = []
        for choice in choices:
            rospy.loginfo('Choice: \n%s', repr(choice))
            if len(choice.values):
                value = choose(choice.values)
                results.append(Result(id=choice.id, value=value))
            else:
                rospy.logwarn('No values for choice "%s" in spec "%s"', choice.id, spec)

        return QueryResult(results=results)


if __name__ == '__main__':
    rospy.init_node('random_answerer')
    HMIServer(rospy.get_name())
    rospy.spin()