#!/usr/bin/env python

import rospy
from hmi_msgs.msg import QueryAction, QueryResult, Result
from actionlib import SimpleActionServer
from random import choice as choose
from hmi_server.abstract_server import AbstractHMIServer, HMIResult


class HMIServer(AbstractHMIServer):

    def _determine_answer(self, description, spec, choices, is_preempt_requested):
        results = {}
        for choice, values in choices.items():
            if len(values):
                value = choose(values)
                results[choice] = value
            else:
                rospy.logwarn('No values for choice "%s" in spec "%s"', choice.id, spec)

        return HMIResult(results=results)


if __name__ == '__main__':
    rospy.init_node('random_answerer')
    HMIServer(rospy.get_name())
    rospy.spin()