#!/usr/bin/env python

import rospy
from hmi_msgs.msg import QueryAction, QueryResult, Result
from actionlib import SimpleActionServer
from random import choice as choose
from hmi_server.abstract_server import AbstractHMIServer, HMIResult


wait_time = 5


class HMIServer(AbstractHMIServer):

    def _determine_answer(self, description, spec, choices, is_preempt_requested):

        rospy.loginfo('Waiting for %d seconds', wait_time)
        start = rospy.Time.now()
        while rospy.Time.now() - start < rospy.Duration(wait_time) \
              and not is_preempt_requested() \
              and not rospy.is_shutdown():
            rospy.sleep(0.1)

        results = {}
        for choice, values in choices.items():
            if len(values):
                value = choose(values)
                results[choice] = value
            else:
                rospy.logwarn('No values for choice "%s" in spec "%s"', choice.id, spec)

        return HMIResult(results=results)


if __name__ == '__main__':
    rospy.init_node('random_answerer')
    HMIServer(rospy.get_name())
    rospy.spin()
