#!/usr/bin/env python

import argparse
import sys

import rospy
from hmi_server.api import Api, TimeoutException

# start the node
rospy.init_node('test_query', anonymous=True)
args = rospy.myargv(argv=sys.argv)

# parse the args
parser = argparse.ArgumentParser()
parser.add_argument('server', nargs='?', default='hmi', help='Actionlib server')

args = parser.parse_args(args[1:])
server = args.server

# do the query
api = Api(server)
try:
    api.query('Choose apple or banana and beer or coke', '<fruit> <drink>',
              {'fruit': ["apple", "banana"], 'drink': ['beer', 'coke']})
except TimeoutException:
    pass
