#!/usr/bin/env python

import argparse
import sys

import rospy
from hmi_server.api import Api

# start the node
rospy.init_node('test_query_raw', anonymous=True)
args = rospy.myargv(argv=sys.argv)

# parse the args
parser = argparse.ArgumentParser()
parser.add_argument('server', nargs='?', default='hmi', help='Actionlib server')
parser.add_argument('query', nargs='?', default='apple|banana', help='Raw query')

args = parser.parse_args(args[1:])
print args
server = args.server
query = args.query

# do the query
api = Api(server)
api.query_raw('', query)
