#!/usr/bin/env python

import argparse
from hmi_server.api import Api
import rospy

parser = argparse.ArgumentParser()
parser.add_argument('server', help='Actionlib server')
parser.add_argument('query', help='Raw query')

args = parser.parse_args()
server = args.server
query = args.query

rospy.init_node('test_query_raw', anonymous=True)
api = Api(server)
api.query_raw('', query)