#!/usr/bin/env python

import argparse
import sys

import rospy
from hmi_server.api import Api

# start the node
rospy.init_node('test_query_raw_from_file', anonymous=True)
args = rospy.myargv(argv=sys.argv)

# parse the args
parser = argparse.ArgumentParser()
parser.add_argument('server', nargs='?', default='hmi', help='Actionlib server')
parser.add_argument('file', help='File containing the raw spec')

args = parser.parse_args(args[1:])
server = args.server
filepath = args.file

with open(filepath, 'r') as f:
    api = Api(server)
    api.query_raw('', f.read())
