#!/usr/bin/env python

import argparse
from hmi_server.api import Api
import rospy

parser = argparse.ArgumentParser()
parser.add_argument('server', help='Actionlib server')

args = parser.parse_args()
server = args.server

rospy.init_node('test_query_raw', anonymous=True)
api = Api(server)
api.query('Choose apple or banana and beer or coke', '<fruit>, <drink>',
          {'fruit': ["apple", "banana"], 'drink': ['beer', 'coke']})
